# Generated by Django 2.0.1 on 2020-10-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_chatinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chatInfo',
        ),
    ]
