# Generated by Django 2.0.1 on 2020-10-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_chatinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chatInfo',
        ),
    ]
