# Generated by Django 2.0.1 on 2020-10-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_delete_chatinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=20)),
                ('sender', models.CharField(max_length=20)),
                ('receiver_name', models.CharField(max_length=20)),
                ('receiver', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
