# Generated by Django 2.0.1 on 2020-09-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('contact_number', models.IntegerField()),
                ('contact_number_2', models.IntegerField()),
                ('email', models.EmailField(max_length=40)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('photo', models.ImageField(default='Not Available', upload_to='organization_images/')),
                ('password', models.CharField(max_length=30)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
