# Generated by Django 2.0.1 on 2020-09-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmodel',
            name='password',
        ),
        migrations.AlterField(
            model_name='organizationmodel',
            name='photo',
            field=models.ImageField(upload_to='organization_images/'),
        ),
    ]
