# Generated by Django 2.0.1 on 2020-09-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nonuser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('cno', models.IntegerField()),
                ('msg', models.TextField(max_length=100)),
            ],
        ),
    ]
