# Generated by Django 2.0.1 on 2020-09-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NonUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonuser',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
