# Generated by Django 2.0.1 on 2020-10-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NonUser', '0002_nonuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonuser',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
