# Generated by Django 2.0.1 on 2020-10-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NonUser', '0003_auto_20201001_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonuser',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
