# Generated by Django 2.0.1 on 2020-10-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NonUser', '0004_auto_20201001_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonuser',
            name='msg',
            field=models.CharField(max_length=100),
        ),
    ]
